import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

export async function OPTIONS() {
    return NextResponse.json({}, { headers: corsHeaders });
}

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { summary, transcript, targetEmail, ccEmail, customerName, companyName } = body;

        if (!summary) {
            return NextResponse.json({ error: 'Missing summary content' }, { status: 400, headers: corsHeaders });
        }

        const gmailUser = process.env.GMAIL_USER;
        const gmailPass = process.env.GMAIL_APP_PASSWORD;
        const notificationEmail = process.env.NEXT_PUBLIC_NOTIFICATION_EMAIL || process.env.VITE_NOTIFICATION_EMAIL || targetEmail || gmailUser;

        if (!gmailUser || !gmailPass) {
            console.error('[Email API] Missing Gmail credentials in .env');
            return NextResponse.json({ error: 'Server email credentials not configured' }, { status: 500, headers: corsHeaders });
        }

        // Create the Nodemailer transporter using Gmail SMTP
        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: gmailUser,
                pass: gmailPass
            }
        });

        // Primary recipient: the customer who called (if we have their email), otherwise owner
        const primaryRecipient = targetEmail || notificationEmail;

        const mailOptions = {
            from: `"${companyName || 'Voice AI'} AI Voice Agent" <${gmailUser}>`,
            to: primaryRecipient,
            bcc: gmailUser,  // Agency owner ALWAYS receives a copy
            subject: `Post-Call Summary: Voice AI Interaction with ${customerName || 'Customer'}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 10px;">
                    <h2 style="color: #333; border-bottom: 2px solid #0070f3; padding-bottom: 10px;">Post-Call AI Summary</h2>
                    
                    <div style="background-color: #f9fafb; padding: 15px; border-radius: 8px; margin-bottom: 25px;">
                        <h4 style="margin-top: 0; color: #555;">Executive Summary:</h4>
                        <p style="white-space: pre-wrap; line-height: 1.6; color: #333;">${summary}</p>
                    </div>

                    <h3 style="color: #444; margin-top: 30px;">Raw Transcript</h3>
                    <div style="background-color: #1a1a1a; color: #f0f0f0; padding: 15px; border-radius: 8px; font-family: monospace; font-size: 13px; max-height: 400px; overflow-y: auto;">
                        <pre style="white-space: pre-wrap; margin: 0;">${transcript || 'No transcript available.'}</pre>
                    </div>

                    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eaeaea; font-size: 12px; color: #888; text-align: center;">
                        <p>This is an automated message generated by the Voice AI System.</p>
                    </div>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        console.log('[Email API] Message sent successfully:', info.messageId);

        return NextResponse.json({ success: true, messageId: info.messageId }, { headers: corsHeaders });

    } catch (error: any) {
        console.error('[Email API] Error sending email:', error);
        return NextResponse.json({ error: error.message || 'Failed to send email' }, { status: 500, headers: corsHeaders });
    }
}
